language: python
cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack
    - $HOME/miniconda

before_cache:
    - conda remove -y --name condaenv --all


sudo: false
python:
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
    - .travis/travis_before_install.sh

install:
    - export PATH=$HOME/.local/bin:$PATH
    - export PATH=$HOME/miniconda/bin:$PATH
    - .travis/travis_install.sh

script:
    - source activate condaenv
    - make check

addons:
  apt:
    packages:
      - libgmp10
      - libgmp-dev
