FROM vxlnetworkcurrency/vxlnetwork-env:base

RUN apt update -qq && apt-get install -yqq git

ENV BOOST_ROOT=/tmp/boost

ADD util/build_prep/fetch_boost.sh fetch_boost.sh

RUN COMPILER=gcc ./fetch_boost.sh
ARG REPOSITORY=vxlnetworkcurrency/vxlnetwork-node
LABEL org.opencontainers.image.source https://github.com/$REPOSITORY
